experiment:
  tracking: "console" # Options: "console", "comet"
  project_name: "cnn_emotion_detection"
  name: "baseline_cnn"
  # api_key: "YOUR_COMET_API_KEY"

data:
  path: "manojdilz/facial_emotion_detection_dataset" # HF Dataset ID
  modality: "vision"
  batch_size: 32
  num_workers: 2
  split_ratio: 0.8 # Train/Val split if dataset doesn't have it

model:
  name: "custom_cnn"
  num_classes: 7 # Angry, Disgust, Fear, Happy, Neutral, Sad, Surprise
  hidden_dim: 256
  dropout: 0.3

training:
  epochs: 15
  lr: 0.0005
  seed: 42
  device: "cuda" # or "cpu", "mps"
  save_dir: "./checkpoints"